### ISSUE TITLE
模块重启挂载不上

### ISSUE THREAD

**Issue by muablog** [Magisk-Modules-Repo/com.piyushgarg.rclone#18]
你好，模块重启后不会自动挂载，并且我尝试手动挂载也挂载不上，只有空文件夹
[GoogleDrive] available at: -> [/mnt/cloud/GoogleDrive]
/sbin/.core/img/com.piyushgarg.rclone/service.sh[414]: su: not found

[Onedrivefuli] available at: -> [/mnt/cloud/Onedrivefuli]
/sbin/.core/img/com.piyushgarg.rclone/service.sh[414]: su: not found

**Comment by piyushgarg** [comment]
@muablog, is your device rooted?
Never had this problem.
Go into adb shell and try su command?

**Comment by Geofferey** [comment]
哪个版本的Magisk?

**Comment by muablog** [comment]
Magisk and modules are up to date

**Comment by muablog** [comment]
> 哪个版本的Magisk？如果你会说英语，那么帮助你会更容易。

Magisk and modules are up to date

**Comment by muablog** [comment]
> @muablog，你的设备是否已植根？
> 从未遇到过这个问题。
> 进入adb shell并尝试su命令？

It's root.，And try the Su command

**Comment by muablog** [comment]
It's strange. I find I don't know when it's already mounted.

**Comment by Geofferey** [comment]
@muablog What is your mount namespace in Magisk Manager settings set as? Are you saying it works sometimes and not others.

**Comment by HASJ** [comment]
I think he is suffering from the same problem I am.

The module does not automatically mount upon reboot and needs to be reinstalled.

**Comment by Geofferey** [comment]
@HASJ I wonder if somehow my updates to dev branch are ending up being delivered prematurely. You said the August 2nd fixed your issues but I just pushed that to my dev branch, which shouldn't be available through Magisk Manager.

**Comment by HASJ** [comment]
I do believe that is the case, @Geofferey.

At first it seemed intentional, as the issue I first reported and you then modified appeared on the repo almost instantly.
But since the broken update, something must be wrong.

And don't worry, I am not using any separate file from the dev branch, only those from the repo (which might be the dev branch, now that I think about it 😐)

**Comment by Geofferey** [comment]
Yup, this issue seems in part due to they way modules repo operates. Whenever I push changes to the dev branch Magisk Manager catches the time last changes were made to repo and thinks there is an update even tho there isn't. 

The module itself isn't broken but when the same version updates over itself it breaks for some reason. I'm gonna look and see what's wrong with Module itself because that shouldn't happen even if it's updating over same version. 

I honestly thought Magisk Manager was only supposed to show updates for a module if it's version code changed. Appears that is not the case :( . I guess I'll have to move all development over to my fork which kinda sucks because I like users to see progress being made before release.
