### ISSUE TITLE
Cannot run on Android 8

### ISSUE THREAD

**Issue by rufengsuixing** [Magisk-Modules-Repo/com.piyushgarg.rclone#35]
trying to run 'rclone' results in nothing, after wait for some time, juicessh crash

**Comment by RaXorX** [comment]
Same stuff happened on Android Q. In my case, my phone stopped working, had to reboot it otherwise nothing worked. Waited for 10 minutes but nothing happened. I first tried using adb (I usually run commands via adb instead of using any terminal app) but it showed nothing. 

Then I installed material terminal, after giving SU permissions running rclone config or rclone resulted in /sbin/.config/rclone/rclone.conf not found repeatedly. I then copied my conf file (from desktop) to .rclone folder in /sdcard with the same result as above. After which, I placed the conf file to "/sdcard/.config/rclone" directory and this time it gave me that crash I mentioned above.

**Comment by rufengsuixing** [comment]
fix by use my own rclone binary
